//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webserver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHATLIEU
    {
        public string IDDONGHO { get; set; }
        public string IDCHATLIEU { get; set; }
        public string SIZEKINH { get; set; }
        public string LOAIKINH { get; set; }
        public string LOAIDAY { get; set; }
        public string CHATLIEU1 { get; set; }
        public string MAUTOMATSO { get; set; }
        public string MAUTOVO { get; set; }
        public string MUCCHONGNUOC { get; set; }
    }
}
