#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webserver.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_CUAHANGDONGHO")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHATLIEU(CHATLIEU instance);
    partial void UpdateCHATLIEU(CHATLIEU instance);
    partial void DeleteCHATLIEU(CHATLIEU instance);
    partial void InsertTHUONGHIEU(THUONGHIEU instance);
    partial void UpdateTHUONGHIEU(THUONGHIEU instance);
    partial void DeleteTHUONGHIEU(THUONGHIEU instance);
    partial void InsertCHITIETHOADON(CHITIETHOADON instance);
    partial void UpdateCHITIETHOADON(CHITIETHOADON instance);
    partial void DeleteCHITIETHOADON(CHITIETHOADON instance);
    partial void InsertDONGHO(DONGHO instance);
    partial void UpdateDONGHO(DONGHO instance);
    partial void DeleteDONGHO(DONGHO instance);
    partial void InsertDONGHOYEUTHICH(DONGHOYEUTHICH instance);
    partial void UpdateDONGHOYEUTHICH(DONGHOYEUTHICH instance);
    partial void DeleteDONGHOYEUTHICH(DONGHOYEUTHICH instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLOAIDONGHO(LOAIDONGHO instance);
    partial void UpdateLOAIDONGHO(LOAIDONGHO instance);
    partial void DeleteLOAIDONGHO(LOAIDONGHO instance);
    partial void InsertQUANTRI(QUANTRI instance);
    partial void UpdateQUANTRI(QUANTRI instance);
    partial void DeleteQUANTRI(QUANTRI instance);
    #endregion
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHATLIEU> CHATLIEUs
		{
			get
			{
				return this.GetTable<CHATLIEU>();
			}
		}
		
		public System.Data.Linq.Table<THUONGHIEU> THUONGHIEUs
		{
			get
			{
				return this.GetTable<THUONGHIEU>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETHOADON> CHITIETHOADONs
		{
			get
			{
				return this.GetTable<CHITIETHOADON>();
			}
		}
		
		public System.Data.Linq.Table<DONGHO> DONGHOs
		{
			get
			{
				return this.GetTable<DONGHO>();
			}
		}
		
		public System.Data.Linq.Table<DONGHOYEUTHICH> DONGHOYEUTHICHes
		{
			get
			{
				return this.GetTable<DONGHOYEUTHICH>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAIDONGHO> LOAIDONGHOs
		{
			get
			{
				return this.GetTable<LOAIDONGHO>();
			}
		}
		
		public System.Data.Linq.Table<QUANTRI> QUANTRIs
		{
			get
			{
				return this.GetTable<QUANTRI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHATLIEU")]
	public partial class CHATLIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDDONGHO;
		
		private string _IDCHATLIEU;
		
		private string _SIZEKINH;
		
		private string _LOAIKINH;
		
		private string _LOAIDAY;
		
		private string _CHATLIEU1;
		
		private string _MAUTOMATSO;
		
		private string _MAUTOVO;
		
		private string _MUCCHONGNUOC;
		
		private EntityRef<DONGHO> _DONGHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDONGHOChanging(string value);
    partial void OnIDDONGHOChanged();
    partial void OnIDCHATLIEUChanging(string value);
    partial void OnIDCHATLIEUChanged();
    partial void OnSIZEKINHChanging(string value);
    partial void OnSIZEKINHChanged();
    partial void OnLOAIKINHChanging(string value);
    partial void OnLOAIKINHChanged();
    partial void OnLOAIDAYChanging(string value);
    partial void OnLOAIDAYChanged();
    partial void OnCHATLIEU1Changing(string value);
    partial void OnCHATLIEU1Changed();
    partial void OnMAUTOMATSOChanging(string value);
    partial void OnMAUTOMATSOChanged();
    partial void OnMAUTOVOChanging(string value);
    partial void OnMAUTOVOChanged();
    partial void OnMUCCHONGNUOCChanging(string value);
    partial void OnMUCCHONGNUOCChanged();
    #endregion
		
		public CHATLIEU()
		{
			this._DONGHO = default(EntityRef<DONGHO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDONGHO", DbType="Char(30)")]
		public string IDDONGHO
		{
			get
			{
				return this._IDDONGHO;
			}
			set
			{
				if ((this._IDDONGHO != value))
				{
					if (this._DONGHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDONGHOChanging(value);
					this.SendPropertyChanging();
					this._IDDONGHO = value;
					this.SendPropertyChanged("IDDONGHO");
					this.OnIDDONGHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCHATLIEU", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDCHATLIEU
		{
			get
			{
				return this._IDCHATLIEU;
			}
			set
			{
				if ((this._IDCHATLIEU != value))
				{
					this.OnIDCHATLIEUChanging(value);
					this.SendPropertyChanging();
					this._IDCHATLIEU = value;
					this.SendPropertyChanged("IDCHATLIEU");
					this.OnIDCHATLIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIZEKINH", DbType="Char(20)")]
		public string SIZEKINH
		{
			get
			{
				return this._SIZEKINH;
			}
			set
			{
				if ((this._SIZEKINH != value))
				{
					this.OnSIZEKINHChanging(value);
					this.SendPropertyChanging();
					this._SIZEKINH = value;
					this.SendPropertyChanged("SIZEKINH");
					this.OnSIZEKINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIKINH", DbType="NVarChar(30)")]
		public string LOAIKINH
		{
			get
			{
				return this._LOAIKINH;
			}
			set
			{
				if ((this._LOAIKINH != value))
				{
					this.OnLOAIKINHChanging(value);
					this.SendPropertyChanging();
					this._LOAIKINH = value;
					this.SendPropertyChanged("LOAIKINH");
					this.OnLOAIKINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIDAY", DbType="NVarChar(30)")]
		public string LOAIDAY
		{
			get
			{
				return this._LOAIDAY;
			}
			set
			{
				if ((this._LOAIDAY != value))
				{
					this.OnLOAIDAYChanging(value);
					this.SendPropertyChanging();
					this._LOAIDAY = value;
					this.SendPropertyChanged("LOAIDAY");
					this.OnLOAIDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CHATLIEU", Storage="_CHATLIEU1", DbType="NVarChar(30)")]
		public string CHATLIEU1
		{
			get
			{
				return this._CHATLIEU1;
			}
			set
			{
				if ((this._CHATLIEU1 != value))
				{
					this.OnCHATLIEU1Changing(value);
					this.SendPropertyChanging();
					this._CHATLIEU1 = value;
					this.SendPropertyChanged("CHATLIEU1");
					this.OnCHATLIEU1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAUTOMATSO", DbType="NVarChar(30)")]
		public string MAUTOMATSO
		{
			get
			{
				return this._MAUTOMATSO;
			}
			set
			{
				if ((this._MAUTOMATSO != value))
				{
					this.OnMAUTOMATSOChanging(value);
					this.SendPropertyChanging();
					this._MAUTOMATSO = value;
					this.SendPropertyChanged("MAUTOMATSO");
					this.OnMAUTOMATSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAUTOVO", DbType="NVarChar(30)")]
		public string MAUTOVO
		{
			get
			{
				return this._MAUTOVO;
			}
			set
			{
				if ((this._MAUTOVO != value))
				{
					this.OnMAUTOVOChanging(value);
					this.SendPropertyChanging();
					this._MAUTOVO = value;
					this.SendPropertyChanged("MAUTOVO");
					this.OnMAUTOVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MUCCHONGNUOC", DbType="Char(9)")]
		public string MUCCHONGNUOC
		{
			get
			{
				return this._MUCCHONGNUOC;
			}
			set
			{
				if ((this._MUCCHONGNUOC != value))
				{
					this.OnMUCCHONGNUOCChanging(value);
					this.SendPropertyChanging();
					this._MUCCHONGNUOC = value;
					this.SendPropertyChanged("MUCCHONGNUOC");
					this.OnMUCCHONGNUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONGHO_CHATLIEU", Storage="_DONGHO", ThisKey="IDDONGHO", OtherKey="IDDONGHO", IsForeignKey=true)]
		public DONGHO DONGHO
		{
			get
			{
				return this._DONGHO.Entity;
			}
			set
			{
				DONGHO previousValue = this._DONGHO.Entity;
				if (((previousValue != value) 
							|| (this._DONGHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONGHO.Entity = null;
						previousValue.CHATLIEUs.Remove(this);
					}
					this._DONGHO.Entity = value;
					if ((value != null))
					{
						value.CHATLIEUs.Add(this);
						this._IDDONGHO = value.IDDONGHO;
					}
					else
					{
						this._IDDONGHO = default(string);
					}
					this.SendPropertyChanged("DONGHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUONGHIEU")]
	public partial class THUONGHIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDTHUONGHIEU;
		
		private string _TENTHUONGHIEU;
		
		private string _HINH;
		
		private EntitySet<DONGHO> _DONGHOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTHUONGHIEUChanging(string value);
    partial void OnIDTHUONGHIEUChanged();
    partial void OnTENTHUONGHIEUChanging(string value);
    partial void OnTENTHUONGHIEUChanged();
    partial void OnHINHChanging(string value);
    partial void OnHINHChanged();
    #endregion
		
		public THUONGHIEU()
		{
			this._DONGHOs = new EntitySet<DONGHO>(new Action<DONGHO>(this.attach_DONGHOs), new Action<DONGHO>(this.detach_DONGHOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTHUONGHIEU", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDTHUONGHIEU
		{
			get
			{
				return this._IDTHUONGHIEU;
			}
			set
			{
				if ((this._IDTHUONGHIEU != value))
				{
					this.OnIDTHUONGHIEUChanging(value);
					this.SendPropertyChanging();
					this._IDTHUONGHIEU = value;
					this.SendPropertyChanged("IDTHUONGHIEU");
					this.OnIDTHUONGHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUONGHIEU", DbType="NVarChar(50)")]
		public string TENTHUONGHIEU
		{
			get
			{
				return this._TENTHUONGHIEU;
			}
			set
			{
				if ((this._TENTHUONGHIEU != value))
				{
					this.OnTENTHUONGHIEUChanging(value);
					this.SendPropertyChanging();
					this._TENTHUONGHIEU = value;
					this.SendPropertyChanged("TENTHUONGHIEU");
					this.OnTENTHUONGHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH", DbType="NVarChar(20)")]
		public string HINH
		{
			get
			{
				return this._HINH;
			}
			set
			{
				if ((this._HINH != value))
				{
					this.OnHINHChanging(value);
					this.SendPropertyChanging();
					this._HINH = value;
					this.SendPropertyChanged("HINH");
					this.OnHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONGHIEU_DONGHO", Storage="_DONGHOs", ThisKey="IDTHUONGHIEU", OtherKey="IDTHUONGHIEU")]
		public EntitySet<DONGHO> DONGHOs
		{
			get
			{
				return this._DONGHOs;
			}
			set
			{
				this._DONGHOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DONGHOs(DONGHO entity)
		{
			this.SendPropertyChanging();
			entity.THUONGHIEU = this;
		}
		
		private void detach_DONGHOs(DONGHO entity)
		{
			this.SendPropertyChanging();
			entity.THUONGHIEU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHOADON")]
	public partial class CHITIETHOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDHOADON;
		
		private string _IDDONGHO;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<double> _THANHTIEN;
		
		private System.Nullable<double> _DONGIA;
		
		private EntityRef<DONGHO> _DONGHO;
		
		private EntityRef<HOADON> _HOADON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHOADONChanging(string value);
    partial void OnIDHOADONChanged();
    partial void OnIDDONGHOChanging(string value);
    partial void OnIDDONGHOChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnTHANHTIENChanging(System.Nullable<double> value);
    partial void OnTHANHTIENChanged();
    partial void OnDONGIAChanging(System.Nullable<double> value);
    partial void OnDONGIAChanged();
    #endregion
		
		public CHITIETHOADON()
		{
			this._DONGHO = default(EntityRef<DONGHO>);
			this._HOADON = default(EntityRef<HOADON>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHOADON", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDHOADON
		{
			get
			{
				return this._IDHOADON;
			}
			set
			{
				if ((this._IDHOADON != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDHOADONChanging(value);
					this.SendPropertyChanging();
					this._IDHOADON = value;
					this.SendPropertyChanged("IDHOADON");
					this.OnIDHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDONGHO", DbType="Char(30)")]
		public string IDDONGHO
		{
			get
			{
				return this._IDDONGHO;
			}
			set
			{
				if ((this._IDDONGHO != value))
				{
					if (this._DONGHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDONGHOChanging(value);
					this.SendPropertyChanging();
					this._IDDONGHO = value;
					this.SendPropertyChanged("IDDONGHO");
					this.OnIDDONGHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Float")]
		public System.Nullable<double> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Float")]
		public System.Nullable<double> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONGHO_CHITIETHOADON", Storage="_DONGHO", ThisKey="IDDONGHO", OtherKey="IDDONGHO", IsForeignKey=true)]
		public DONGHO DONGHO
		{
			get
			{
				return this._DONGHO.Entity;
			}
			set
			{
				DONGHO previousValue = this._DONGHO.Entity;
				if (((previousValue != value) 
							|| (this._DONGHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONGHO.Entity = null;
						previousValue.CHITIETHOADONs.Remove(this);
					}
					this._DONGHO.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADONs.Add(this);
						this._IDDONGHO = value.IDDONGHO;
					}
					else
					{
						this._IDDONGHO = default(string);
					}
					this.SendPropertyChanged("DONGHO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CHITIETHOADON", Storage="_HOADON", ThisKey="IDHOADON", OtherKey="IDHOADON", IsForeignKey=true)]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CHITIETHOADON = null;
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADON = this;
						this._IDHOADON = value.IDHOADON;
					}
					else
					{
						this._IDHOADON = default(string);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONGHO")]
	public partial class DONGHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDDONGHO;
		
		private string _TENDONGHO;
		
		private System.Nullable<double> _GIABAN;
		
		private string _XUATSU;
		
		private string _GIOITINH;
		
		private string _IDLOAI;
		
		private string _IDTHUONGHIEU;
		
		private string _HINH;
		
		private EntitySet<CHATLIEU> _CHATLIEUs;
		
		private EntitySet<CHITIETHOADON> _CHITIETHOADONs;
		
		private EntitySet<DONGHOYEUTHICH> _DONGHOYEUTHICHes;
		
		private EntityRef<THUONGHIEU> _THUONGHIEU;
		
		private EntityRef<LOAIDONGHO> _LOAIDONGHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDONGHOChanging(string value);
    partial void OnIDDONGHOChanged();
    partial void OnTENDONGHOChanging(string value);
    partial void OnTENDONGHOChanged();
    partial void OnGIABANChanging(System.Nullable<double> value);
    partial void OnGIABANChanged();
    partial void OnXUATSUChanging(string value);
    partial void OnXUATSUChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnIDLOAIChanging(string value);
    partial void OnIDLOAIChanged();
    partial void OnIDTHUONGHIEUChanging(string value);
    partial void OnIDTHUONGHIEUChanged();
    partial void OnHINHChanging(string value);
    partial void OnHINHChanged();
    #endregion
		
		public DONGHO()
		{
			this._CHATLIEUs = new EntitySet<CHATLIEU>(new Action<CHATLIEU>(this.attach_CHATLIEUs), new Action<CHATLIEU>(this.detach_CHATLIEUs));
			this._CHITIETHOADONs = new EntitySet<CHITIETHOADON>(new Action<CHITIETHOADON>(this.attach_CHITIETHOADONs), new Action<CHITIETHOADON>(this.detach_CHITIETHOADONs));
			this._DONGHOYEUTHICHes = new EntitySet<DONGHOYEUTHICH>(new Action<DONGHOYEUTHICH>(this.attach_DONGHOYEUTHICHes), new Action<DONGHOYEUTHICH>(this.detach_DONGHOYEUTHICHes));
			this._THUONGHIEU = default(EntityRef<THUONGHIEU>);
			this._LOAIDONGHO = default(EntityRef<LOAIDONGHO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDONGHO", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDDONGHO
		{
			get
			{
				return this._IDDONGHO;
			}
			set
			{
				if ((this._IDDONGHO != value))
				{
					this.OnIDDONGHOChanging(value);
					this.SendPropertyChanging();
					this._IDDONGHO = value;
					this.SendPropertyChanged("IDDONGHO");
					this.OnIDDONGHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDONGHO", DbType="NVarChar(50)")]
		public string TENDONGHO
		{
			get
			{
				return this._TENDONGHO;
			}
			set
			{
				if ((this._TENDONGHO != value))
				{
					this.OnTENDONGHOChanging(value);
					this.SendPropertyChanging();
					this._TENDONGHO = value;
					this.SendPropertyChanged("TENDONGHO");
					this.OnTENDONGHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABAN", DbType="Float")]
		public System.Nullable<double> GIABAN
		{
			get
			{
				return this._GIABAN;
			}
			set
			{
				if ((this._GIABAN != value))
				{
					this.OnGIABANChanging(value);
					this.SendPropertyChanging();
					this._GIABAN = value;
					this.SendPropertyChanged("GIABAN");
					this.OnGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XUATSU", DbType="NVarChar(50)")]
		public string XUATSU
		{
			get
			{
				return this._XUATSU;
			}
			set
			{
				if ((this._XUATSU != value))
				{
					this.OnXUATSUChanging(value);
					this.SendPropertyChanging();
					this._XUATSU = value;
					this.SendPropertyChanged("XUATSU");
					this.OnXUATSUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(10)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLOAI", DbType="Char(10)")]
		public string IDLOAI
		{
			get
			{
				return this._IDLOAI;
			}
			set
			{
				if ((this._IDLOAI != value))
				{
					if (this._LOAIDONGHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDLOAIChanging(value);
					this.SendPropertyChanging();
					this._IDLOAI = value;
					this.SendPropertyChanged("IDLOAI");
					this.OnIDLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTHUONGHIEU", DbType="Char(10)")]
		public string IDTHUONGHIEU
		{
			get
			{
				return this._IDTHUONGHIEU;
			}
			set
			{
				if ((this._IDTHUONGHIEU != value))
				{
					if (this._THUONGHIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTHUONGHIEUChanging(value);
					this.SendPropertyChanging();
					this._IDTHUONGHIEU = value;
					this.SendPropertyChanged("IDTHUONGHIEU");
					this.OnIDTHUONGHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH", DbType="NVarChar(50)")]
		public string HINH
		{
			get
			{
				return this._HINH;
			}
			set
			{
				if ((this._HINH != value))
				{
					this.OnHINHChanging(value);
					this.SendPropertyChanging();
					this._HINH = value;
					this.SendPropertyChanged("HINH");
					this.OnHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONGHO_CHATLIEU", Storage="_CHATLIEUs", ThisKey="IDDONGHO", OtherKey="IDDONGHO")]
		public EntitySet<CHATLIEU> CHATLIEUs
		{
			get
			{
				return this._CHATLIEUs;
			}
			set
			{
				this._CHATLIEUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONGHO_CHITIETHOADON", Storage="_CHITIETHOADONs", ThisKey="IDDONGHO", OtherKey="IDDONGHO")]
		public EntitySet<CHITIETHOADON> CHITIETHOADONs
		{
			get
			{
				return this._CHITIETHOADONs;
			}
			set
			{
				this._CHITIETHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONGHO_DONGHOYEUTHICH", Storage="_DONGHOYEUTHICHes", ThisKey="IDDONGHO", OtherKey="IDDONGHO")]
		public EntitySet<DONGHOYEUTHICH> DONGHOYEUTHICHes
		{
			get
			{
				return this._DONGHOYEUTHICHes;
			}
			set
			{
				this._DONGHOYEUTHICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONGHIEU_DONGHO", Storage="_THUONGHIEU", ThisKey="IDTHUONGHIEU", OtherKey="IDTHUONGHIEU", IsForeignKey=true)]
		public THUONGHIEU THUONGHIEU
		{
			get
			{
				return this._THUONGHIEU.Entity;
			}
			set
			{
				THUONGHIEU previousValue = this._THUONGHIEU.Entity;
				if (((previousValue != value) 
							|| (this._THUONGHIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUONGHIEU.Entity = null;
						previousValue.DONGHOs.Remove(this);
					}
					this._THUONGHIEU.Entity = value;
					if ((value != null))
					{
						value.DONGHOs.Add(this);
						this._IDTHUONGHIEU = value.IDTHUONGHIEU;
					}
					else
					{
						this._IDTHUONGHIEU = default(string);
					}
					this.SendPropertyChanged("THUONGHIEU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIDONGHO_DONGHO", Storage="_LOAIDONGHO", ThisKey="IDLOAI", OtherKey="IDLOAI", IsForeignKey=true)]
		public LOAIDONGHO LOAIDONGHO
		{
			get
			{
				return this._LOAIDONGHO.Entity;
			}
			set
			{
				LOAIDONGHO previousValue = this._LOAIDONGHO.Entity;
				if (((previousValue != value) 
							|| (this._LOAIDONGHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIDONGHO.Entity = null;
						previousValue.DONGHOs.Remove(this);
					}
					this._LOAIDONGHO.Entity = value;
					if ((value != null))
					{
						value.DONGHOs.Add(this);
						this._IDLOAI = value.IDLOAI;
					}
					else
					{
						this._IDLOAI = default(string);
					}
					this.SendPropertyChanged("LOAIDONGHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHATLIEUs(CHATLIEU entity)
		{
			this.SendPropertyChanging();
			entity.DONGHO = this;
		}
		
		private void detach_CHATLIEUs(CHATLIEU entity)
		{
			this.SendPropertyChanging();
			entity.DONGHO = null;
		}
		
		private void attach_CHITIETHOADONs(CHITIETHOADON entity)
		{
			this.SendPropertyChanging();
			entity.DONGHO = this;
		}
		
		private void detach_CHITIETHOADONs(CHITIETHOADON entity)
		{
			this.SendPropertyChanging();
			entity.DONGHO = null;
		}
		
		private void attach_DONGHOYEUTHICHes(DONGHOYEUTHICH entity)
		{
			this.SendPropertyChanging();
			entity.DONGHO = this;
		}
		
		private void detach_DONGHOYEUTHICHes(DONGHOYEUTHICH entity)
		{
			this.SendPropertyChanging();
			entity.DONGHO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONGHOYEUTHICH")]
	public partial class DONGHOYEUTHICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDDONGHO;
		
		private string _IDKHACHHANG;
		
		private EntityRef<DONGHO> _DONGHO;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDONGHOChanging(string value);
    partial void OnIDDONGHOChanged();
    partial void OnIDKHACHHANGChanging(string value);
    partial void OnIDKHACHHANGChanged();
    #endregion
		
		public DONGHOYEUTHICH()
		{
			this._DONGHO = default(EntityRef<DONGHO>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDONGHO", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDDONGHO
		{
			get
			{
				return this._IDDONGHO;
			}
			set
			{
				if ((this._IDDONGHO != value))
				{
					if (this._DONGHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDONGHOChanging(value);
					this.SendPropertyChanging();
					this._IDDONGHO = value;
					this.SendPropertyChanged("IDDONGHO");
					this.OnIDDONGHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKHACHHANG", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDKHACHHANG
		{
			get
			{
				return this._IDKHACHHANG;
			}
			set
			{
				if ((this._IDKHACHHANG != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._IDKHACHHANG = value;
					this.SendPropertyChanged("IDKHACHHANG");
					this.OnIDKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONGHO_DONGHOYEUTHICH", Storage="_DONGHO", ThisKey="IDDONGHO", OtherKey="IDDONGHO", IsForeignKey=true)]
		public DONGHO DONGHO
		{
			get
			{
				return this._DONGHO.Entity;
			}
			set
			{
				DONGHO previousValue = this._DONGHO.Entity;
				if (((previousValue != value) 
							|| (this._DONGHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONGHO.Entity = null;
						previousValue.DONGHOYEUTHICHes.Remove(this);
					}
					this._DONGHO.Entity = value;
					if ((value != null))
					{
						value.DONGHOYEUTHICHes.Add(this);
						this._IDDONGHO = value.IDDONGHO;
					}
					else
					{
						this._IDDONGHO = default(string);
					}
					this.SendPropertyChanged("DONGHO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONGHOYEUTHICH", Storage="_KHACHHANG", ThisKey="IDKHACHHANG", OtherKey="EMAIL", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.DONGHOYEUTHICHes.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.DONGHOYEUTHICHes.Add(this);
						this._IDKHACHHANG = value.EMAIL;
					}
					else
					{
						this._IDKHACHHANG = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDHOADON;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
		private System.Nullable<double> _TONGTIEN;
		
		private string _IDKHACHHANG;
		
		private EntityRef<CHITIETHOADON> _CHITIETHOADON;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHOADONChanging(string value);
    partial void OnIDHOADONChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    partial void OnTONGTIENChanging(System.Nullable<double> value);
    partial void OnTONGTIENChanged();
    partial void OnIDKHACHHANGChanging(string value);
    partial void OnIDKHACHHANGChanged();
    #endregion
		
		public HOADON()
		{
			this._CHITIETHOADON = default(EntityRef<CHITIETHOADON>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHOADON", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDHOADON
		{
			get
			{
				return this._IDHOADON;
			}
			set
			{
				if ((this._IDHOADON != value))
				{
					this.OnIDHOADONChanging(value);
					this.SendPropertyChanging();
					this._IDHOADON = value;
					this.SendPropertyChanged("IDHOADON");
					this.OnIDHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Float")]
		public System.Nullable<double> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKHACHHANG", DbType="Char(30)")]
		public string IDKHACHHANG
		{
			get
			{
				return this._IDKHACHHANG;
			}
			set
			{
				if ((this._IDKHACHHANG != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._IDKHACHHANG = value;
					this.SendPropertyChanged("IDKHACHHANG");
					this.OnIDKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CHITIETHOADON", Storage="_CHITIETHOADON", ThisKey="IDHOADON", OtherKey="IDHOADON", IsUnique=true, IsForeignKey=false)]
		public CHITIETHOADON CHITIETHOADON
		{
			get
			{
				return this._CHITIETHOADON.Entity;
			}
			set
			{
				CHITIETHOADON previousValue = this._CHITIETHOADON.Entity;
				if (((previousValue != value) 
							|| (this._CHITIETHOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHITIETHOADON.Entity = null;
						previousValue.HOADON = null;
					}
					this._CHITIETHOADON.Entity = value;
					if ((value != null))
					{
						value.HOADON = this;
					}
					this.SendPropertyChanged("CHITIETHOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_KHACHHANG", ThisKey="IDKHACHHANG", OtherKey="EMAIL", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._IDKHACHHANG = value.EMAIL;
					}
					else
					{
						this._IDKHACHHANG = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _EMAIL;
		
		private string _PASS;
		
		private string _HOTEN;
		
		private string _GIOITINH;
		
		private System.Nullable<int> _NAMSINH;
		
		private string _SDT;
		
		private string _NOISINH;
		
		private EntitySet<DONGHOYEUTHICH> _DONGHOYEUTHICHes;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnPASSChanging(string value);
    partial void OnPASSChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNAMSINHChanging(System.Nullable<int> value);
    partial void OnNAMSINHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNOISINHChanging(string value);
    partial void OnNOISINHChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._DONGHOYEUTHICHes = new EntitySet<DONGHOYEUTHICH>(new Action<DONGHOYEUTHICH>(this.attach_DONGHOYEUTHICHes), new Action<DONGHOYEUTHICH>(this.detach_DONGHOYEUTHICHes));
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS", DbType="Char(30)")]
		public string PASS
		{
			get
			{
				return this._PASS;
			}
			set
			{
				if ((this._PASS != value))
				{
					this.OnPASSChanging(value);
					this.SendPropertyChanging();
					this._PASS = value;
					this.SendPropertyChanged("PASS");
					this.OnPASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(10)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMSINH", DbType="Int")]
		public System.Nullable<int> NAMSINH
		{
			get
			{
				return this._NAMSINH;
			}
			set
			{
				if ((this._NAMSINH != value))
				{
					this.OnNAMSINHChanging(value);
					this.SendPropertyChanging();
					this._NAMSINH = value;
					this.SendPropertyChanged("NAMSINH");
					this.OnNAMSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOISINH", DbType="NVarChar(20)")]
		public string NOISINH
		{
			get
			{
				return this._NOISINH;
			}
			set
			{
				if ((this._NOISINH != value))
				{
					this.OnNOISINHChanging(value);
					this.SendPropertyChanging();
					this._NOISINH = value;
					this.SendPropertyChanged("NOISINH");
					this.OnNOISINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONGHOYEUTHICH", Storage="_DONGHOYEUTHICHes", ThisKey="EMAIL", OtherKey="IDKHACHHANG")]
		public EntitySet<DONGHOYEUTHICH> DONGHOYEUTHICHes
		{
			get
			{
				return this._DONGHOYEUTHICHes;
			}
			set
			{
				this._DONGHOYEUTHICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_HOADONs", ThisKey="EMAIL", OtherKey="IDKHACHHANG")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DONGHOYEUTHICHes(DONGHOYEUTHICH entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_DONGHOYEUTHICHes(DONGHOYEUTHICH entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIDONGHO")]
	public partial class LOAIDONGHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDLOAI;
		
		private string _TENLOAI;
		
		private string _HINH;
		
		private EntitySet<DONGHO> _DONGHOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDLOAIChanging(string value);
    partial void OnIDLOAIChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    partial void OnHINHChanging(string value);
    partial void OnHINHChanged();
    #endregion
		
		public LOAIDONGHO()
		{
			this._DONGHOs = new EntitySet<DONGHO>(new Action<DONGHO>(this.attach_DONGHOs), new Action<DONGHO>(this.detach_DONGHOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLOAI", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDLOAI
		{
			get
			{
				return this._IDLOAI;
			}
			set
			{
				if ((this._IDLOAI != value))
				{
					this.OnIDLOAIChanging(value);
					this.SendPropertyChanging();
					this._IDLOAI = value;
					this.SendPropertyChanged("IDLOAI");
					this.OnIDLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(50)")]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH", DbType="NVarChar(20)")]
		public string HINH
		{
			get
			{
				return this._HINH;
			}
			set
			{
				if ((this._HINH != value))
				{
					this.OnHINHChanging(value);
					this.SendPropertyChanging();
					this._HINH = value;
					this.SendPropertyChanged("HINH");
					this.OnHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIDONGHO_DONGHO", Storage="_DONGHOs", ThisKey="IDLOAI", OtherKey="IDLOAI")]
		public EntitySet<DONGHO> DONGHOs
		{
			get
			{
				return this._DONGHOs;
			}
			set
			{
				this._DONGHOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DONGHOs(DONGHO entity)
		{
			this.SendPropertyChanging();
			entity.LOAIDONGHO = this;
		}
		
		private void detach_DONGHOs(DONGHO entity)
		{
			this.SendPropertyChanging();
			entity.LOAIDONGHO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUANTRI")]
	public partial class QUANTRI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _EMAIL;
		
		private string _PASS;
		
		private string _HOTEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnPASSChanging(string value);
    partial void OnPASSChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    #endregion
		
		public QUANTRI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS", DbType="Char(30)")]
		public string PASS
		{
			get
			{
				return this._PASS;
			}
			set
			{
				if ((this._PASS != value))
				{
					this.OnPASSChanging(value);
					this.SendPropertyChanging();
					this._PASS = value;
					this.SendPropertyChanged("PASS");
					this.OnPASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
