//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webserver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONGHO
    {
        public string IDDONGHO { get; set; }
        public string TENDONGHO { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public string XUATSU { get; set; }
        public string GIOITINH { get; set; }
        public string IDLOAI { get; set; }
        public string IDTHUONGHIEU { get; set; }
        public string HINH { get; set; }
    }
}
