//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webserver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int IDHOADON { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string IDKHACHHANG { get; set; }
    }
}
